
# Import Packages
```{r}

# Installs pacman if needed
if (!require("pacman")) install.packages("pacman")

# load packages
pacman::p_load(
    pacman, 
    rio,       # data importing
    dplyr,     # data manipulation
    ggplot2,   # ploting
    stringr,   # string formatting
    scales,    # plot scales and color etc. 
    viridis,   # color palette
    hrbrthemes,# plot themes
    plotly     # interactive plot
    )

```

# Import Dataset
```{r}

dataset_path <- "./dataset/"

daily_covid <- import(
    paste0(dataset_path, "worldometer_coronavirus_daily_data.csv"))
head(daily_covid)

summary_covid <- import(
    paste0(dataset_path, "worldometer_coronavirus_summary_data.csv"))
head(summary_covid)

```
# Data Cleaning
```{r}

# daily_covid[is.na(d)] <- 0

```

# Data Manipulation and visualization
## Generic Questions and Answers
```{r}

## global percentage of death, active case and recovered ##

# sum vertically
categories <- c("total_deaths", "total_recovered", "active_cases")
category <- str_replace_all(categories, pattern =  "_", replacement = " ")
category <- str_to_title(category)

data <- 
    summary_covid[, categories] %>%
    colSums(na.rm = T)
data <- data.frame(
  category=category,
  count=data
)

data$prettyCount <- prettyNum(data$count, big.mark = ",", scientific = F)

# Compute percentages
data$fraction <- data$count / sum(data$count)

# Compute the cumulative percentages (top of each rectangle)
data$ymax <- cumsum(data$fraction)

# Compute the bottom of each rectangle
data$ymin <- c(0, head(data$ymax, n=-1))

# Compute label position
data$labelPosition <- (data$ymax + data$ymin) / 2

# Compute a good label
# data$label <- paste(data$prettyCount, "\n", data$category)

# Compute display percentages
data$prettyFraction <- percent(data$fraction)

# Make the plot
ggplot(data, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=category)) +
    geom_rect() +
    geom_text( 
        x=4.3, 
        aes(y=labelPosition, label=prettyCount, color=category, fontface="bold"), 
        size=3.5
    ) + # x here controls label position (inner / outer)
    geom_text(
        x=3.5, 
        aes(y=labelPosition, label=prettyFraction, fontface="bold"), 
        color="white",
        size=4
    ) +
    scale_fill_brewer(palette="Set2") +
    scale_color_brewer(palette="Set2") +
    coord_polar(theta="y") +
    xlim(c(2, 4)) +
    theme_void() +
    annotate(
        geom = "text", 
        x = 2, 
        y = 0, 
        label = paste0(
            "Total Cases\n", 
            prettyNum(sum(data$count), big.mark = ",", scientific = F
            )
        )
    )
    # theme(legend.position = "none")

```

```{r}
## comparison of cases between different continent ##


```

```{r}

# overview of accumulated cases vs date for all the country


# ranking of cases for the top n countries
# use tree map

```

```{r}
summary_covid
```


## More in depth Questions
```{r fig.align="center", fig.width = 12, fig.height = 6}
# what is the relation between population and covid cases

data <- 
    select(
        summary_covid, 
        total_confirmed, 
        population, 
        continent, 
        total_tests
    ) %>%
    arrange(desc(total_tests)) # to prevent big bubble overlapping small ones

p <- 
    ggplot(
        data, 
        aes(x=population, y=total_confirmed, fill=continent, size=total_tests)
    ) +
    geom_point(alpha=0.5, shape=21, color="black") +
    scale_x_log10(
        labels = unit_format(unit = "M", scale = 1e-6),
        breaks = 1e+3 * 10^(seq(0,8,2)),
    ) +
    scale_y_log10(
        labels = unit_format(unit = "M", scale = 1e-6),
        breaks = 10 * 10^(seq(0,8,2)),
    ) +
    scale_size(range = c(2, 35), name="Total Tests") +
    ylab("Covid Cases") +
    xlab("Population") +
    coord_cartesian(clip = "off") +
    theme_ipsum() +
    scale_fill_viridis(discrete=TRUE, option = "A")

p
```

# clean up
```{r}

pacman::p_unload(all)

```

